# Chapter-5 Collections
This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [261]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating environment at `C:\Users\KIIT\Downloads\Hands-on-Julia-Programming-main\Chapter 05\Project.toml`
  Activating environment at `C:\Users\KIIT\Downloads\Hands-on-Julia-Programming-main\Chapter 05\Project.toml`


## 5.1 Predefined Data Structures

Julia language has defined a few standard data structures like

- Arrays
- Tuples
- Dicts
- Sets

## 5.2 Tuple

Immutable data type with a number of comma separated values. We have seen tuples as arguments to functions. Here we shall explore the collection like behavior of a tuples.

In [262]:
a = (1, "string", 1.0)


(1, "string", 1.0)

(1, "string", 1.0)

In [263]:
typeof(a)                         # Heterogeneous

Tuple{Int64, String, Float64}

Tuple{Int64, String, Float64}

In [264]:
a[1]                              # Accessed as Index

1

1

In [265]:
a[1] = 6                          # Immutable

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

In [266]:
b, c = a                          # Pattern Matching
(1, "string", 1.0)

(1, "string", 1.0)

(1, "string", 1.0)

In [267]:
b

1

1

In [268]:
c

"string"

"string"

### NTuple

N elements of a specific type in a tuple like collection.

In [269]:
NTuple{3, Int}

Tuple{Int64, Int64, Int64}

Tuple{Int64, Int64, Int64}

In [270]:
a = ntuple(x->4, 10)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

In [271]:
typeof(a)

NTuple{10, Int64}

NTuple{10, Int64}

In [272]:
a = ntuple(i->i*1.0, 10)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

In [273]:
typeof(a)

NTuple{10, Float64}

NTuple{10, Float64}

### Tuple as a Collection

A `Tuple` has collection like properties like it has length method. Can be iterated over. 

In [274]:
length(a)

10

10

In [275]:
for i=1:length(a)
    println(a[i])
end

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


### Integers as Type Parameters

We saw with `NTuple` an integer `N` being used as a type parameter. We discuss about a Point type which can have N-axes. Then we define Point{2} and Point{3} as special cases for 2 and 3 dimentsions. 

In [276]:
struct Point{N}
    data::NTuple{N, Float32}
    Point(d...)=new{length(d)}(d)
end
const Point2D=Point{2}
const Point3D=Point{3}

function dist(p1::Point2D, p2::Point2D)
    dx, dy = (p1.data[1] - p2.data[1], p1.data[2] - p2.data[2])
    return sqrt(dx*dx+dy*dy)
end
function dist(p1::Point3D, p2::Point3D)
    dx, dy, dz = (p1.data[1] - p2.data[1], 
                  p1.data[2] - p2.data[2], 
                  p1.data[3] - p2.data[3])
    return sqrt(dx*dx+dy*dy+dz*dz)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [277]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [278]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

3.4641016f0

In [279]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [280]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [281]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

3.4641016f0

In [282]:
function dist(p1::Point, p2::Point)
    N = length(p1.data)
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [283]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

2.828427f0

In [284]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))


LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

In [285]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

function dist(p1::Point{N1}, p2::Point{N2}) where {N1, N2}
    N1 > N2 && return dist(p2, p1)
    tp = Point(p1.data..., ntuple(i->0f0, N2-N1)...)
    return dist(tp, p2)
end

dist (generic function with 4 methods)

dist (generic function with 4 methods)

In [286]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))

3.0f0

3.0f0

### Value Parameters

Dispatch based on an integer value. 

In [287]:
struct MyVal{N}
    MyVal(N)=new{N}()
end
f(::MyVal{N}) where N = N
function f(::MyVal{1})
    println("Called from 1")
end

f (generic function with 2 methods)

f (generic function with 2 methods)

In [288]:
f(MyVal(2))

2

2

In [289]:
f(MyVal(1))

Called from 1
Called from 1


#### Singleton

In [290]:
MyVal(1) === MyVal(1)

true

true

In [291]:
MyVal(1) === MyVal(2)

false

false

In [292]:
MyVal(:a)

MyVal{:a}()

MyVal{:a}()

## 5.3 Ranges

Sequence of numbers maintaining a steady pattern. 

### UnitRange
Range of consecutive integers. 

In [293]:
a=1:5
typeof(a)

UnitRange{Int64}

UnitRange{Int64}

In [294]:
for i=a
    println(i)
end

1
2
3
4
5
1
2
3
4
5


### StepRange

Ranges where integers are not consecutive but spaced by a step. 

In [295]:
b=1:2:5
typeof(b)

StepRange{Int64, Int64}

StepRange{Int64, Int64}

In [296]:
for i=b
    println(i)
end

1
3
5
1
3
5


### Decreasing Ranges

Ranges that are decreasing in value with a negative step. 

In [297]:
c=5:-1:1
typeof(c)

StepRange{Int64, Int64}

StepRange{Int64, Int64}

In [298]:
for i=c
    println(i)
end


5
4
35
4
3
2
1

2
1


In [299]:
d = 1:2.1:6.0

1.0:2.1:5.2

1.0:2.1:5.2

In [300]:
typeof(d)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

## 5.4 Array
Mutable collection with a well defined memory layout.

In [301]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

3-element Vector{Int64}:
 1
 2
 3

In [302]:
m = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

1×3 Matrix{Int64}:
 1  2  3

In [303]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [304]:
m2 = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

### Memory Layout and Indexing

In [305]:
m1[1, 2]

2

2

In [306]:
m1[2, 2]

5

5

In [307]:
m2[1, 2]

2

2

In [308]:
m2[2, 2]

4

4

#### Effects of Paging

### Some Useful Functions

#### Constructors

In [309]:
Array{Int}(undef, 1, 2)

1×2 Matrix{Int64}:
 7218764622419096931  1795189868

1×2 Matrix{Int64}:
 7218764622419096931  1795189868

In [310]:
Array{Int}(undef, 2)

2-element Vector{Int64}:
 7218817673670192995
          1509977196

2-element Vector{Int64}:
 7218817673670192995
          1509977196

In [311]:
Array{Int, 2}(undef, (2, 3))

2×3 Matrix{Int64}:
 297964368  297964432  297964496
 297964400  297964464  297964528

2×3 Matrix{Int64}:
 297964368  297964432  297964496
 297964400  297964464  297964528

In [312]:
Array{Float32}(undef, (2, 3))

2×3 Matrix{Float32}:
 7.21486f-28  7.21163f-28  7.21271f-28
 0.0          0.0          0.0

2×3 Matrix{Float32}:
 7.21486f-28  7.21163f-28  7.21271f-28
 0.0          0.0          0.0

In [313]:
struct A
    i::Int
    f::Float64
end
a = A(1, 1); isbits(a)

true

true

In [314]:
aarr = Array{A}(undef, (2, 2))

2×2 Matrix{A}:
 A(140721509263361, 4.94e-322)  A(20, 1.5e-323)
 A(1000, 1.235e-321)            A(32, 2.0e-323)

2×2 Matrix{A}:
 A(140721509263361, 4.94e-322)  A(20, 1.5e-323)
 A(1000, 1.235e-321)            A(32, 2.0e-323)

In [315]:
struct T
    a::A
    b
end
b = T(A(1, 1), 1); isbits(b)

false

false

In [316]:
barr = Array{T}(undef, (2, 2))

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

In [317]:
barr[1,1] = barr[2,1] = barr[1,2] = barr[2,2] = b

T(A(1, 1.0), 1)

T(A(1, 1.0), 1)

In [318]:
barr

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

In [319]:
Vector{Int}(undef, 3)

3-element Vector{Int64}:
 1531852848
 1531852880
 1531852912

3-element Vector{Int64}:
 1531852848
 1531852880
 1531852912

In [320]:
Matrix{Int}(undef, 3, 3)

3×3 Matrix{Int64}:
 4048795878384940900  7378083891455277111  7090126180480267063
 3472384379911168819  3907207169739732068  3472664773394851121
 7306302292035199538  7221634588133647156           1800832512

3×3 Matrix{Int64}:
 4048795878384940900  7378083891455277111  7090126180480267063
 3472384379911168819  3907207169739732068  3472664773394851121
 7306302292035199538  7221634588133647156           1800832512

#### zeros and ones

In [321]:
zeros(Float32, (2, 3))

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [322]:
ones(Float32, (2, 3))

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [323]:
ones(UInt8, (2, 3))

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

#### trues and falses

Return `BitArray`, which are optimal `Array{Bool}` like types but take 1/8-th of the space. 

In [324]:
zb = zeros(Bool, (8, 8))

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [325]:
sizeof(zb)

64

64

In [326]:
z = falses(8, 8)

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [327]:
sizeof(z)

8

8

#### fill and similar

In [328]:
a = fill(5.0, (2, 2))

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [329]:
a = fill(5, (2, 2))

2×2 Matrix{Int64}:
 5  5
 5  5

2×2 Matrix{Int64}:
 5  5
 5  5

In [330]:
b = similar(a, Int)

2×2 Matrix{Int64}:
 1512567664   242745536
  242745600  1533993440

2×2 Matrix{Int64}:
 1512567664   242745536
  242745600  1533993440

#### collect

Enumerates over a collection and return an array with all elements populated. 

In [331]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

3-element Vector{Int64}:
 1
 2
 3

In [332]:
collect(Float64, 1:2:3)

2-element Vector{Float64}:
 1.0
 3.0

2-element Vector{Float64}:
 1.0
 3.0

#### reshape

Reshape an array to various sizes while keeping the row major ordering intact.

In [333]:
a = collect(1:16)

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

In [334]:
b = reshape(a, (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [335]:
c = reshape(b, (2, 8))

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

In [336]:
d = reshape(c, (8, 2))

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

#### hcat, vcat and hvcat

Concatenation of arrays vertically, horizontally or both when the dimensions are aligned properly. 

In [337]:
vcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [338]:
hcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

In [339]:
hvcat((2, 2, 2), [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

In [340]:
hvcat(6, [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

## 5.5 Associative Collection

A collection where a key and value are kept associated. The keys are used for accessing the elements of the collection. 

### Dict

A hash based dictionary.

In [341]:
d = Dict("a"=>1, "c"=>2, "b"=>3)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 1

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 1

In [342]:
d["b"]

3

3

In [343]:
d["a"] = 5

5

5

In [344]:
println(d)

Dict("c" => 2, "b" => 3, "a" => 5)
Dict("c" => 2, "b" => 3, "a" => 5)


In [345]:
d = Dict("a"=>1, "c"=>2, "b"=>3, "a"=>4)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 4

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 4

#### get Methods

In [346]:
get(d, "a", 3)

4

4

In [347]:
get(d, "e", 0)

0

0

In [348]:
getindex(d, "e")

LoadError: KeyError: key "e" not found

LoadError: KeyError: key "e" not found

In [349]:
d["e"]

LoadError: KeyError: key "e" not found

LoadError: KeyError: key "e" not found

In [350]:
get!(d, "a", 0)

4

4

In [351]:
get!(d, "e", 0)

0

0

In [352]:
d

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 0
  "b" => 3
  "a" => 4

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 0
  "b" => 3
  "a" => 4

#### setindex! Method

In [353]:
d["e"] = 10

10

10

In [354]:
setindex!(d, 11, "e")

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 11
  "b" => 3
  "a" => 4

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 11
  "b" => 3
  "a" => 4

### Set

Collection of belonging. Unique elements only. 

In [355]:
s = Set([2 3 4 5 1 2 3])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [356]:
6 in s

false

false

In [357]:
5 in s

true

true

In [358]:
t = Set([4 5 7 8 9])

Set{Int64} with 5 elements:
  5
  4
  7
  9
  8

Set{Int64} with 5 elements:
  5
  4
  7
  9
  8

#### Union and Intersection

In [359]:
union(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [360]:
intersect(s, t)

Set{Int64} with 2 elements:
  5
  4

Set{Int64} with 2 elements:
  5
  4

In [361]:
union!(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [362]:
s

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

## 5.6 Iteration 

All collections are enabled for iteration. This requires the collections to implement certain interfaces / functions. 

### for loop

In [363]:
for i=5:-2:1
    println(i)
end

5
3
1
5
3
1


In [364]:
b = [1.0 2 3; 4 5 6; 7 8 9]
for i=b
    println(i)
end

1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0
1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0


In [365]:
for p in d
    println(p)
end

"c" => 2
"e" => 11
"b" => 3
"a" => 4
"c" => 2
"e" => 11
"b" => 3
"a" => 4


In [366]:
for (k, v) in d
    println("Key:", k," Value:", v)
end

Key:c Value:2
Key:e Value:11
Key:b Value:3
Key:a Value:4
Key:c Value:2
Key:e Value:11
Key:b Value:3
Key:a Value:4


### function...do

A very neat way to code for function that applies to every element of the collection. `map` is a useful method that is in-built to address such needs. 

In [367]:
function collect_square(v)
    a = similar(v)
    for i=1:length(v)
        a[i] = v[i]*v[i]
    end
    return a
end
collect_square(1:4)

4-element Vector{Int64}:
  1
  4
  9
 16

4-element Vector{Int64}:
  1
  4
  9
 16

In [368]:
function collect_function(f::Function, v)
    a = similar(v)
    for i=1:length(v)
        a[i] = f(v[i])
    end
    return a
end
collect_function(x->x^3, 1:4)

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

In [369]:
collect_function(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

In [370]:
map(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

4-element Vector{Int64}:
  1
  8
 27
 64

## 5.7 Iteration Framework

Custom collection authors must implement the iteration framework. 

In [371]:
v = collect(3:2:10)

4-element Vector{Int64}:
 3
 5
 7
 9

4-element Vector{Int64}:
 3
 5
 7
 9

In [372]:
for i=v
    println(i)
end

3
5
7
9
3
5
7
9


In [373]:
next = iterate(v)

(3, 2)

(3, 2)

In [374]:
while next !== nothing
    value, state = next
    println(value)
    next = iterate(v, state)
end


3
5
7
9
3
5
7
9


### iterate Methods

### Optional Methods

In [375]:
Base.IteratorSize(Vector{Int})

Base.HasShape{1}()

Base.HasShape{1}()

In [376]:
Base.IteratorEltype(Vector{Int})

Base.HasEltype()

Base.HasEltype()

In [377]:
eltype(Vector{Int})

Int64

Int64

### Example

In [378]:
struct Squares
    value::Int
end
Base.iterate(s::Squares) = s.value <= 0 ? nothing : (1, 2)

Base.iterate(s::Squares, state) = s.value < state ? nothing :      
    (state*state, state+1)

In [379]:
for i=Squares(3)
    println(i)
end

1
4
9
1
4
9


In [380]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [381]:
Base.length(s::Squares)=s.value

In [382]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [383]:
Base.eltype(::Type{Squares})=Int

In [384]:
eltype(Squares)

Int64

Int64

In [385]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

## 5.8 Generators and Comprehensions

Comprehensions are a simple notation to create arrays. Generators provide the iterator interface and elements get computed only when iterated upon. 

In [386]:
[i*i for i=1:3]

3-element Vector{Int64}:
 1
 4
 9

3-element Vector{Int64}:
 1
 4
 9

In [387]:
[i*j for i=1:3, j=1:3]

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [388]:
[i*j for i=1:3 for j=i:3]

6-element Vector{Int64}:
 1
 2
 3
 4
 6
 9

6-element Vector{Int64}:
 1
 2
 3
 4
 6
 9

In [389]:
gen=(i*j for i=1:3 for j=i:3)

Base.Iterators.Flatten{Base.Generator{UnitRange{Int64}, var"#70#71"}}(Base.Generator{UnitRange{Int64}, var"#70#71"}(var"#70#71"(), 1:3))

Base.Iterators.Flatten{Base.Generator{UnitRange{Int64}, var"#70#71"}}(Base.Generator{UnitRange{Int64}, var"#70#71"}(var"#70#71"(), 1:3))

In [390]:
for v=gen
    println(v)
end

11
2
3
4
6
9

2
3
4
6
9
